name: "Run a script"
description: "-"
inputs:
  pattern:
    description: Pattern
    required: true
    default: "-iname '*.yml' -o -iname '*.yaml'"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        find . -type f \( ${{ inputs.pattern }} \)
