name: Call From Test
on:
  workflow_call:
  workflow_dispatch:

jobs:
  callme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - uses: ./.github/actions/simpleaction
